# judge_model: gpt-4.5-preview (This judge is goated)

# judge_model: gemini-2.5
# temperature: 1.0
# max_tokens: 32000

# judge_model: gpt-4.1
# temperature: 0.0
# max_tokens: 16000

judge_model: gpt-4.1-mini
temperature: 0.0
max_tokens: 16000

bench_name: arena-hard-v2.0

reference: null

regex_patterns:
  - \[\[([AB<>=]+)\]\]
  - \[([AB<>=]+)\]

prompt_template: "<|User Prompt|>\n{QUESTION}\n\n<|The Start of Assistant A's Answer|>\n{ANSWER_A}\n<|The End of Assistant A's Answer|>\n\n<|The Start of Assistant B's Answer|>\n{ANSWER_B}\n<|The End of Assistant B's Answer|>"

model_list:
  - llama3.2-1b-offline-dpo-beta-0.01-lr-0.0005-v6
  - llama3.2-1b-offline-dpo-beta-0.01-lr-0.0005-with-len-norm-v6
  - llama3.2-1b-offline-simpo-beta-0.01-lr-0.0003-gamma-to-beta-1.4-v6
  - llama3.2-1b-offline-simpo-beta-0.01-lr-0.0003-gamma-to-beta-1.4-no-len-norm-v6
  - llama3.2-1b-offline-mmpo-beta-0.5-lr-0.0003-reward_eps_0.6-v6
  - llama3.2-1b-offline-mmpo-beta-0.5-lr-0.0003-reward_eps_0.6-with-len-norm-v6
  - llama3.2-1b-sftdatasetv3-sft-checkpoint-111000


